[project]
name = 'Tokenized-Industrial-Equipment-Sharing-Platform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.owner-verification]
path = 'contracts/owner-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.payment-settlement]
path = 'contracts/payment-settlement.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
